blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Manabu-GT/DebugOverlay-Android/discussions
    about: Please ask questions and share ideas here first.
