build:
  maxIssues: 0

config:
  validation: true

processors:
  active: true

# Tweak common Android/Kotlin rules
style:
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
  WildcardImport:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ReturnCount:
    active: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: true
