name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Caches Gradle + wrapper automatically
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Single entrypoint runs Spotless + Detekt + Android Lint + Unit tests
      # (Spotless and Detekt are hooked into `check` by AGP)
      - name: Run checks
        run: ./gradlew check --continue --stacktrace

      # Try to upload even when detekt finds issues if SARIF files exist
      - name: Upload SARIF to GitHub Code Scanning
        if: always() && hashFiles('**/build/reports/detekt/detekt.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '**/build/reports/detekt/detekt.sarif'

      - name: Build Project
        run: ./gradlew clean assembleDebug --stacktrace
