name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Caches Gradle + wrapper automatically
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Run checks (Spotless + Detekt + Lint + Tests), then merge SARIF reports
      # detekt is hooked into subproject `check` tasks, so it runs automatically
      # reportMerge must run after to collect all SARIF files
      - name: Run checks
        run: ./gradlew check reportMerge --continue --stacktrace

      # Upload merged SARIF report to GitHub Code Scanning
      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/reports/detekt/merge.sarif

      - name: Build Project
        run: ./gradlew clean assembleDebug --stacktrace
