name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        # Caches Gradle + wrapper automatically

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck

      - name: Android Lint
        run: ./gradlew lintDebug

      - name: Build Project
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
